# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# Suppress FutureWarnings from docutils about deprecated embed_images setting
import warnings
warnings.filterwarnings("ignore", category=FutureWarning, module="docutils")


# -- Project information -----------------------------------------------------

project = 'User Guide - Logicrays'
copyright = '2011-2025 by LogicRays Technologies, All Rights Reserved'
author = 'LogicRays Technologies'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '1.0.0'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Performance optimization: Enable parallel reading for faster builds
numfig = True
numfig_secnum_depth = 2

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# Add hover extension: "hoverxref.extension",
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",  # Link to other project documentation
    "sphinx.ext.viewcode",     # Add links to source code
    "sphinx_copybutton",       # Add copy buttons to code blocks
    "sphinxcontrib.video",
    "sphinx_tabs.tabs",
    "sphinx-prompt",
    "notfound.extension",
    "sphinxemoji.sphinxemoji",
    "sphinx_design",
    "sphinx_sitemap",
]

# Intersphinx mapping - Link to external documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
    # Docker and Git don't have objects.inv files, so removed
}

# Intersphinx timeout
intersphinx_timeout = 10

# Copy button configuration - exclude prompts from being copied
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True
copybutton_remove_prompts = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
# source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '*.md', 'README.md']

# Adding Custom robots.txt
html_extra_path = ["_html"]

# The name of the Pygments (syntax highlighting) style to use.
# Available styles: 'default', 'emacs', 'friendly', 'colorful', 'autumn', 'murphy', 'manni',
# 'material', 'monokai', 'perldoc', 'pastie', 'borland', 'trac', 'native', 'fruity', 'bw',
# 'vim', 'vs', 'tango', 'rrt', 'xcode', 'igor', 'paraiso-light', 'paraiso-dark', 'lovelace',
# 'algol', 'algol_nu', 'arduino', 'rainbow_dash', 'abap', 'solarized-dark', 'solarized-light',
# 'sas', 'stata', 'stata-light', 'stata-dark', 'inkpot'
pygments_style = 'monokai'  # Dark theme for better readability
pygments_dark_style = 'monokai'  # For dark mode if theme supports it

# Language-specific code highlighting configuration
# Don't set a default language - let Pygments auto-detect or use 'none' for plain text
# This prevents warnings when code blocks contain shell/bash commands
highlight_language = 'none'  # Use 'none' to avoid forcing Python syntax on all blocks
highlight_options = {
    'stripall': True,  # Remove leading/trailing whitespace
}

# Code block options
code_show_permalinks = True  # Show permalink on code blocks
add_code_annotations = True  # Enable code annotations

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
    'style_nav_header_background': '#2980B9',
    # ToC options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']
html_static_path = [
  '_static',
  '_static/custom.css'
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'DipakDocsdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'DipakDocs.tex', 'Logicrays Docs Documentation',
     'Dipak Prajapati', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'dipakdocs', 'Logicrays Docs Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'DipakDocs', 'Logicrays Docs Documentation',
     author, 'DipakDocs', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
# epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
# epub_exclude_files = ['search.html']

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# Google Search Console verification and SEO meta tags
html_context = {
    'google_site_verification': 'ENidBsBFI_7AQiHb98Z9BwoidiZGuIOD0y91KP6Govo',
    'meta_description': 'Comprehensive documentation for web development including Magento 2, PHP, Docker, Linux, and development best practices by Dipak Prajapati.',
    'meta_keywords': 'Magento 2, PHP, Docker, Linux, Web Development, Dipak Prajapati, Developer Documentation, Magento Development, DevOps',
    # Content Security Policy for enhanced security
    'csp_policy': "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://www.clarity.ms https://*.clarity.ms; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: http:; connect-src 'self' https://www.google-analytics.com https://www.clarity.ms https://*.clarity.ms; frame-src https://www.googletagmanager.com;",
    # Performance hints - resources to preload/prefetch
    'preload_resources': [
        {'href': '_static/custom.css', 'as': 'style'},
        {'href': 'https://fonts.googleapis.com', 'as': 'connect', 'crossorigin': 'anonymous'},
    ],
    'prefetch_resources': [
        'https://www.googletagmanager.com',
        'https://www.google-analytics.com',
        'https://www.clarity.ms',
    ],
}

# Sitemap configuration for sphinx-sitemap extension
html_baseurl = 'https://dipakp-docs.readthedocs.io/'
sitemap_url_scheme = "{link}"
sitemap_locales = [None]
sitemap_filename = "site-sitemap.xml"

# Additional HTML options for better SEO
html_use_index = True
html_split_index = False
html_copy_source = False
html_show_copyright = True
html_compact_lists = True

# Show last updated date (helps with SEO freshness signals)
html_last_updated_fmt = '%b %d, %Y'

# Page metadata for better organization
html_use_opensearch = 'https://dipakp-docs.readthedocs.io'

# Favicon configuration (helps with brand recognition)
# html_favicon = '_static/favicon.ico'

# Additional meta tags for better indexing
html_additional_pages = {}

# Enable HTML5 writer for better semantic HTML
html_experimental_html5_writer = False

myst_enable_extensions = [
    "deflist",
]

#hoverxref_intersphinx = [
#    "sphinx",
#    "pip",
#    "nbsphinx",
#    "myst-nb",
#    "ipywidgets",
#    "jupytext",
#]
#
#hoverxref_auto_ref = True
#hoverxref_domains = ["py"]
#hoverxref_roles = [
#    "option",
#    "doc",  # Documentation pages
#    "term",  # Glossary terms
#]
#hoverxref_role_types = {
#    "mod": "modal",  # for Python Sphinx Domain
#    "doc": "modal",  # for whole docs
#    "class": "tooltip",  # for Python Sphinx Domain
#    "ref": "tooltip",  # for hoverxref_auto_ref config
#    "confval": "tooltip",  # for custom object
#    "term": "tooltip",  # for glossaries
#}
#hoverxref_ignore_refs = [
#]
